'use client';
import {useMemo,useState} from 'react';
type Profile={name:string;city:string;state:string;skills:string[];mode:string;bio:string;sponsored:boolean};
const profiles:Profile[]=[
{name:'Marina Costa',city:'Porto Alegre',state:'RS',skills:['Musculação','Emagrecimento'],mode:'Presencial e online',bio:'Treinos personalizados para construir uma rotina que cabe na sua vida.',sponsored:true},
{name:'Rafael Oliveira',city:'Santa Cruz do Sul',state:'RS',skills:['Musculação','Condicionamento'],mode:'Presencial',bio:'Acompanhamento individual para treinar com orientação.',sponsored:true},
{name:'Camila Ribeiro',city:'Florianópolis',state:'SC',skills:['Emagrecimento','Corrida'],mode:'Presencial e online',bio:'Planejamento de treino adaptado ao seu nível e objetivos.',sponsored:false},
{name:'Lucas Martins',city:'Curitiba',state:'PR',skills:['Musculação','Corrida'],mode:'Online',bio:'Consultoria de treino com acompanhamento remoto.',sponsored:false}];
export default function Home(){
const [city,setCity]=useState(''),[state,setState]=useState('Todos'),[mode,setMode]=useState('Todos'),[skill,setSkill]=useState('Todas'),[screen,setScreen]=useState<'search'|'plans'>('search'),[selected,setSelected]=useState<Profile|null>(null);
const results=useMemo(()=>profiles.filter(p=>(!city||p.city.toLocaleLowerCase('pt-BR').includes(city.trim().toLocaleLowerCase('pt-BR')))&&(state==='Todos'||p.state===state)&&(mode==='Todos'||p.mode.includes(mode))&&(skill==='Todas'||p.skills.includes(skill))).sort((a,b)=>Number(b.sponsored)-Number(a.sponsored)),[city,state,mode,skill]);
return <><header><button className="logo" onClick={()=>{setScreen('search');setSelected(null)}}><b>P<span>+</span></b> personal<strong>brasil</strong></button><nav><button className={screen==='search'?'active':''} onClick={()=>{setScreen('search');setSelected(null)}}>Encontrar personal</button><button className={screen==='plans'?'active':''} onClick={()=>{setScreen('plans');setSelected(null)}}>Sou personal</button></nav></header>
{screen==='search'&&!selected&&<main><div className="intro"><small>ENCONTRE QUEM TREINA COM VOCÊ</small><h1>O personal certo para <em>o seu próximo passo.</em></h1><p>Busque profissionais pela sua cidade, modalidade e forma de atendimento.</p></div><section className="search"><div className="fields"><label>Cidade<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Digite sua cidade"/></label><label>Estado<select value={state} onChange={e=>setState(e.target.value)}><option value="Todos">Todos os estados</option>{['RS','SC','PR'].map(x=><option key={x}>{x}</option>)}</select></label><label>Atendimento<select value={mode} onChange={e=>setMode(e.target.value)}><option value="Todos">Qualquer atendimento</option><option>Presencial</option><option>Online</option></select></label><button className="action" onClick={()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth'})}>Buscar personais ↗</button></div><div className="chips"><span>Modalidade</span>{['Todas','Musculação','Emagrecimento','Corrida','Condicionamento'].map(x=><button key={x} className={skill===x?'chosen':''} onClick={()=>setSkill(x)}>{x==='Todas'?'Todas as modalidades':x}</button>)}</div></section><section id="results" className="results"><div className="heading"><div><small>PROFISSIONAIS</small><h2>Conheça os profissionais</h2></div><span>{results.length} {results.length===1?'perfil encontrado':'perfis encontrados'}</span></div><p className="demo">Perfis fictícios para demonstração. Nenhum profissional foi verificado nesta versão.</p><div className="grid">{results.map((p,i)=><article className="card" key={p.name}><div className={'avatar color'+i}>{p.name.split(' ').map(x=>x[0]).join('')}</div><div className="content"><div className="meta">{p.sponsored&&<b>PATROCINADO</b>}{p.city} · {p.state}</div><h3>{p.name}</h3><p>{p.bio}</p><div className="tags">{p.skills.map(x=><span key={x}>{x}</span>)}</div><div className="foot"><span>{p.mode}</span><button onClick={()=>setSelected(p)}>Ver perfil ↗</button></div></div></article>)}</div>{results.length===0&&<div className="empty"><h3>Nenhum perfil nesta busca</h3><p>Tente outra cidade, estado ou modalidade.</p><button onClick={()=>{setCity('');setState('Todos');setMode('Todos');setSkill('Todas')}}>Limpar filtros</button></div>}</section></main>}
{screen==='search'&&selected&&<main className="detail"><button className="back" onClick={()=>setSelected(null)}>← Voltar aos resultados</button><article className="detail-box"><div className="avatar">{selected.name.split(' ').map(x=>x[0]).join('')}</div><div><div className="meta">{selected.sponsored&&<b>PATROCINADO</b>}{selected.city} · {selected.state}</div><h1>{selected.name}</h1><p>{selected.bio}</p><div className="tags">{selected.skills.map(x=><span key={x}>{x}</span>)}</div><p>Atendimento: {selected.mode}</p><aside>Perfil ilustrativo. O contato e a comprovação do CREF serão liberados após o cadastro e a verificação dos profissionais.</aside></div></article></main>}
{screen==='plans'&&<main className="plans-page"><small>PARA PROFISSIONAIS</small><h1>Seu trabalho merece <em>ser encontrado.</em></h1><p>Crie seu perfil, informe suas especialidades e apareça nas buscas dos alunos da sua região.</p><div className="plan-grid"><article><small>CADASTRO</small><h2>Essencial</h2><div className="price">R$ 19,90 <span>/ mês</span></div><p>Perfil nas buscas compatíveis com sua cidade, modalidade e atendimento.</p><ul><li>Perfil profissional</li><li>Especialidades e cidades atendidas</li><li>Verificação de CREF após análise</li></ul></article><article className="dark"><small>MAIS VISIBILIDADE</small><h2>Destaque</h2><div className="price">Em definição</div><p>Posições patrocinadas nas buscas compatíveis com seu perfil.</p><ul><li>Tudo do Essencial</li><li>Presença na área patrocinada</li><li>Identificação clara de anúncio</li></ul></article><article><small>PRESENÇA AMPLIADA</small><h2>Premium</h2><div className="price">Em definição</div><p>Mais espaço para apresentar serviços e acompanhar o interesse no perfil.</p><ul><li>Tudo do Destaque</li><li>Perfil ampliado</li><li>Métricas de visitas e contatos</li></ul></article></div><aside><b>Cadastro em preparação.</b> Os planos são uma prévia e ainda não aceitam pagamento.</aside></main>}
<footer><strong>personal<span>brasil</span></strong><span>Encontre orientação para o seu treino.</span></footer></>}
